### PR TITLE
Fixes Issue With New Geckolib Changes to Ensure Armor Model Uniqueness.

### PR DESCRIPTION
**Pull request by AzureDoom**

### CODE REVIEW

**Comment by NielsPilgaard** [comment]
Could you perhaps backport this to 1.16.5? :) We're running into this issue there as well: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/5098

**Comment by starluneaux** [comment]
I'm actually having trouble getting it to compile, but I am working on it!

**Comment by NielsPilgaard** [comment]
Ah I see - Good to hear!

**Comment by AzureDoom** [comment]
Please ensure you have updated Geckolib

**Comment by NielsPilgaard** [comment]
This happened using [geckolib-forge-1.16.5-3.0.81.jar](https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3847907) :)

**Comment by AzureDoom** [comment]
Log please?

**Comment by NielsPilgaard** [comment]
Link to the reporters crash report: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/5098#issuecomment-1189930192

**Comment by AzureDoom** [comment]
It's because they needed to update Geckolib in their dev I believe. @MintTeaTx do you still need help with that?

**Comment by AzureDoom** [comment]
#8 and #9 for updating Geckolib, a slight armor fix we fixed recently with our [GeoArmorItem](https://github.com/bernie-g/geckolib/commit/9cb0dd31d029a95e3173f6a4d22f32c002b3e169), and a backport of the fix to 1.16.5

**Pull request merged**
